### ISSUE TITLE
Validate require, minOccurs, maxOccurs

### ISSUE THREAD

**Issue by xoob** [highsource/jsonix#103]
Great to see occurence support added in #101.

It would be good if jsonix could validate that required fields are present when unmarshalling an XML document. If a required field is missing, jsonix should throw an error.

This is already done for other things, like enum values: https://github.com/highsource/jsonix/blob/master/nodejs/scripts/jsonix.js#L2667

**Comment by highsource** [comment]
I'm a bit sceptic about validation. Enums were required because they can't
be typesafely converted otherwise.

But validating occurence or facets would probably go to far, it is from my
point of view not really the scope of Jsonix.

In this case I think it woule be better to generate a JSON Schema and to
validate JSON against that schema using a JSON Schema validator like AJV.
What do you think?

**Comment by highsource** [comment]
Closing as `wontfix` as validation is not in the scope of Jsonix.

**Comment by ainthek** [comment]
if validation is out of scope what is the purpose of required property inside typeInfos ?
propertyInfos: [{
            name: 'contractStateCode',
            required: true,
            elementName: 'ContractStateCode',
            typeInfo: 'Token'
          }, {

thanx

**Comment by highsource** [comment]
Some folks use this information for tasks like UI generation. This `required` attribute is provided by the underlying schema model libs so it's easy to generate. But Jsonix has never had validation in the scope.

**Comment by ainthek** [comment]
So ma it  VERY clear in docs at least. To avoid more of us confused users.
Thanx man
