### ISSUE TITLE
Support for RelaxNG

### ISSUE THREAD

**Issue by coderextreme** [highsource/jsonix#105]
What effect might this project have on validating JSON against RelaxNG or XSD instead of JSON schema? https://msv.java.net/  The project appears to be a converter from XSD to RelaxNG among others.  Not quite sure what's there and it's  Halloween here.

**Comment by highsource** [comment]
Please move to `jsonix-schema-compiler`. And that will probably be WONTFIX because of this:

https://java.net/jira/browse/JAXB-1068

The unerlying technology (XJC) does not support RelaxNG. So I'm somewhat limiten in options here. I probably won't be able to implement full RelaxNG support on my own.

I'm surely aware of MSV, I know JAXB RI internals pretty well. But there's a giant step between being able to parse or validate and being able to generate class-like structures.

**Comment by highsource** [comment]
Closing this as WONTFIX as it's the wrong project. Please create an issue in the jsonix-schema-compiler. I'll leave it open, but, a I wrote earlier can't really promise it will be implemented. That'd be a hard one.
