### ISSUE TITLE
[Chrome 47 64-bit] Calling Jsonix.Context([...]) results in "Uncaught RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by jabbink** [highsource/jsonix#114]
XSD used: http://docs.oasis-open.org/ubl/os-UBL-2.1/xsd/maindoc/UBL-Invoice-2.1.xsd

Gets stuck in this line: https://github.com/highsource/jsonix/blob/master/scripts/src/main/javascript/org/hisrc/jsonix/Jsonix/Model/ClassInfo.js#L80

**Comment by highsource** [comment]
Could you please send me a pull request with a basic test case which reproduces the problem?

Please add a test project here:

https://github.com/highsource/jsonix-support/u/ubl

See this test project for example:

https://github.com/highsource/jsonix-support/tree/master/l/lightstalker89

I'll at least need your generated mappings and JS code which you use to create the context.

**Comment by highsource** [comment]
Thank you very much for the prompt submission of the test case. Reproduced, will look into it. Looks like infinite recursion.

**Comment by highsource** [comment]
Ok, the problem is in the `Invoice.js`  mapping here:

```
{
        localName: 'TextType',
        baseTypeInfo: '.TextType'
}
```

The `TextType` is defined recursively.

This happens because you compile with `-p Invoice`. Basically you're putting everything in one package. But there are two `TextType`s in different schemas, this is why things mix up.

You have a complex schema with many namespaces. You can't put everything in one package because of the collisions, so you can't use `-p <package>`.

Instead, you can use bindings files to specify packages:

```xml
<jaxb:bindings version="1.0" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" 
	jaxb:extensionBindingPrefixes="xjc">

	<jaxb:bindings 
		schemaLocation="../schema/2.1/xsd/common/CCTS_CCT_SchemaModule-2.1.xsd " 
		node="/xs:schema">
		<jaxb:schemaBindings>
			<jaxb:package name="CCTS_CCT"/>
		</jaxb:schemaBindings>
	</jaxb:bindings>

...
</jaxb:bindings>
```

I've customized your schemas to give you an example and fixed `index.js` to use new mappings, it works now - at least the context gets successfully created.

**Comment by jabbink** [comment]
Thank you for your time :+1:.

I did not look into what the command line command exactly did and just started from the `README.md` which contains the `-p` parameter. Tomorrow I have time to work on this again and see if the rest of the functionality works with your fixes to the schema :heart:.

**Comment by jabbink** [comment]
Tested and it works perfectly. Thanks again!
