### ISSUE TITLE
Using xpath to map application data to marshalled xml

### ISSUE THREAD

**Issue by jefffriesen** [highsource/jsonix#146]
I need to produce large, schema-valid xml documents based on our apps data model. Based on the jasonix documentation, it looks like I would generate the mappings from the xsd schema (PO in the examples). Then to create the xml, I would create a large declarative JS object with the data dynamically set, like this: 

```js
// appData is an object that holds all of our apps data
var doc = marshaller.marshalDocument({
    name: {
        localPart: "purchaseOrder"
    },
    value: {
        orderDate: appData.orderDate,
        shipTo: {
            country: appData.shippingAddress.country,
            name: appData.shippingAddress.name,
            street: appData.shippingAddress.street,
            city: appData.shippingAddress.city,
            state: appData.shippingAddress.state,
            zip: appData.shippingAddress.zip
        },
        items: appData.orderItems.map(item => /* return array of objects */ )
    }
});
```

We're working with a very large schema and xml documents, so this file could get massive and fairly complex. All of the fields in our app already have field definitions, like this:
```js
{
  name: "CAZ Ambient CO",
  label: "Ambient CO",
  outputColumn: "caz_ambient_co",
  description: "Ambient Carbon Monoxide in Parts Per Million. Should not exceed 35 ppm per BPI Protocol.",
  suffix: "PPM",
  decimals: 0,
  hasImproved: true,
  csv: "CAZ > %{n} Ambient CO"

  // Could this work?
  // xpath: 'Building/BuildingDetails/HealthAndSafety/CombustionAppliances/CombustionApplianceZone/AmountAmbientCOinCAZduringTesting'  
},
```

Is it possible that in our data field definitions we could assign an xpath to each field and then use that to generate the xml document in jsonix, instead of the declarative mapping in the JSON object?

**Comment by highsource** [comment]
Hi,

Short answer: not impossible, but I don't thing it would be a right feature for Jsonix.

Long answer:

If I understood it correctly, your problem is that there is a certain structural distance between the XML structure and your business objects. So when you generate mappings from your XML schema, they are quite close to the original XML structure but still quite far from your business objects. So you basically still need business objects->DTO conversion which you'd like to automate with path expressions.

I see two ways to approach the task:

* Allow usage of path expressions in mappings so that you could map directly to your business objects.
* Provide some kind of mechanism to map between DTOs and business objects.

The first approach won't really work for many reasons. For instance, you can't really generate these mappings anymore - so you'd have to say goodbye to the "almost-guaranteed-to-be-schema-conforming" mappings. They'll be ugly, there will be a huge number of corner cases etc. I don't think it's a feasible approach.

The second approach is, essentially, JavaScript Object<->Object mapping which I don't see in Jsonix scope. I think there must be tools to do this, something like [JOLT](https://github.com/bazaarvoice/jolt), for instance.

Or maybe I misunderstood your idea?

Best wishes,
Alexey

**Comment by jefffriesen** [comment]
I think you did understand my idea and I agree that mapping between JS objects is the right approach. However, why I think this *may* be appropriate for the Jasonix library is because that mapping could be (in theory?) done via xpath.

Another way to say this is that I think there is an xpath that maps to the marshaled xml. So you could transform an xpath into a JS data object that gets or sets values in the unmarshalled Jasonix object. 

For example, I'm currently modifying xml files in javascript by taking advantage of Lodash's `_.get()` and `_.set()`. To do that, I have to convert the xpath to a path that Lodash can work with:
```
/HPXML/Building[1]/BuildingDetails/HealthAndSafety/CombustionAppliances/CombustionApplianceZone[1]/SystemIdentifier/$/id
// Transforms to:
HPXML.Building[1].BuildingDetails[0].HealthAndSafety[0].CombustionAppliances[0].CombustionApplianceZone[1].SystemIdentifier[0].$.id
```

I do that on several nodes that I want to insert into the xml with something like this:
```
const elements = [
 {value: `cazzone${index + 1}`, xpath: `/HPXML/Building[0]/BuildingDetails/HealthAndSafety/CombustionAppliances/CombustionApplianceZone[${index}]/SystemIdentifier/$/id`}, 
 {...}, 
 {...}
]

const xmlAsJS = await xml2js.parseStringAsync(xmlString)

const updatedJS = elements
  .map(element => convertXPathToJsPath(element))
  .reduce((acc, element) => _.set(acc, element.jspath, element.value), xmlAsJS)

// convert JS back to xml using xml2js
```

This works ok for a small number of nodes that need inserting. It gets tedious as it gets bigger. More importantly, there is no way to enforce the generation of a valid xml file based on the schema.  It's just not a scalable solution for working with large xml files. 

It seems like Jasonix already does 95% of what's needed. I don't know what API would be best, but I'm thinking you could pass in a simple mapping object when marshaling the xml that is a map of the values and the xpath that you want to show up in the xml. So in our application, we have this defined already:
```js
{
  // bizField: 'xpath/a/b/c' 
  "CAZ Ambient CO": 'Building/BuildingDetails/HealthAndSafety/CombustionAppliances/...'
}
```
Then we transform that into something that Jasonix accepts when marshaling the xml:
```js
[
 {value: 23, xpath: 'Building/BuildingDetails/HealthAndSafety/CombustionAppliances/...'},
 {value: 24, xpath: 'Building/....'}
]
```
I know it's a long response (thank you if you're still reading). But the end result is that Jasonix would accept that last mapping shown above and generate the xml with those values. 

Hope that makes sense.

**Comment by jefffriesen** [comment]
I forgot to say why I think this would be helpful. Assigning an xpath to every field in the app that needs to show up in the xml is much simpler and more concise than creating a large nested mapping of keys/values like I wrote in my first code snippet in my original comment.

**Comment by highsource** [comment]
One thing is for sure - I won't go for XPath based mappings from/to XML. This will lead to parsing and interpreting XPath or XPath-like expressions on XML structures (on unmarshalling) or, which is much worse, constructing XML according to XPath on marshalling. You'll also probably need some kind of expression evaluation and/or templating. This will be way too complex, I won't be able to handle this.

Next, you're interested in XML Schema conforming XML and your schema seems to be quite large. This means the only feasible option is to generate mappings out of the XML Schema automatically. In this case you have to create DTOs for marshalling first. And XPath isn't the right expression language for that, DTOs are JSON, not XML. Moreover, properties in JSON may be named differently compared to elements/attributes in XML. So XPath suiting target XML won't necessarily suit DTOs JSON (which has to be created).

I understand that XPath-based mappings may seem to be a nice idea at first approach. But in non-trivial cases the actual task is to transform between two tree structures according to some rules. In XML world, that's what XSLT does. It's basically the same thing here but between JSON and XML or JSON and Jsonix-JSON. No matter the syntax, the complexity of transformation remains. Unfortunatelly, I don't think I'm capable of implementing a supporting XSLT-like engine for JSON-JSON or JSON-XML transformations in Jsonix. That's just way too complex. You might want to check existing JSON-JSON transformation engines.

I'd suggest to start with a few examples of how you would create Jsonix DTOs for marshalling out of your business objects at the moment. Maybe we'll then see what exactly is complex or cumbersome and could be optimized with limited effort. Or maybe there'll already be a suitable tool out there. I really think JSON-JSON conversions is no the right task for Jsonix. This seems like a good standalone task so I think a better approach would be to combine to focused tools rather than shift the focus of Jsonix.

**Comment by jefffriesen** [comment]
@highsource what you're saying makes sense. And if I am going JSON->SON, then you're right, it would be better done in a different tool. Thanks for the feedback. I'm going to close this and do as you suggest.
