### ISSUE TITLE
unmarshalString is synchronous

### ISSUE THREAD

**Issue by jnj16180340** [highsource/jsonix#155]
In contrast to `unmarshalURL` and `unmarshalFile`, `unmarshalString` and `unmarshalDocument` are asynchronous and do not take a callback function. This can be a bit confusing when refactoring stuff, etc.

I'd be happy with a README note to this effect, but making `unmarshalString` and `unmarshalDocument` async would also work. Thoughts?

**Comment by highsource** [comment]
Well, `unmarshalString` and `unmarshalDocument` are sync by nature as they don't rely on async operations. Unlike `unmarshalURL` and `unmarshalFile` they don't do any IO. The documentation does not explicitly say that but it's quite clear from the code examples:

https://github.com/highsource/jsonix/wiki/Using-Jsonix-in-Your-JavaScript-Program#unmarshalling

Feel free to edit the wiki pages.

Since it's easy to asyncronize sync methods but is hard to synchronize async methods, I'd leave these two methods sync. We may, however refactor these methods to accept an optional callback function - the result will be returned both as the result of the method as well as into the callback function. I'm not sure if it's worth doing, these methods will still be different compared to `unmarshalURL` and `unmarshalFile`. I'd leave it as it is.

**Comment by jnj16180340** [comment]
Oops, I didn't think to look at the wiki
