### ISSUE TITLE
Ignore unknown elements

### ISSUE THREAD

**Issue by samuel-girard** [highsource/jsonix#187]
Hello @highsource 

We are using jsonix to parse WMS GetCapabilities. It works great in most cases, but when using a "customized" GetCapabilities, it fails with marshalling errors.
For example, when trying with this one: [http://services.data.shom.fr/ncwms2/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities](http://services.data.shom.fr/ncwms2/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities), it fails on the edal:ExtendedCapabilities element.

I saw that it is possible to tell jsonix to ignore unknown elements (with the allowDom option).
More generally, we would like JSONIX to unmarshall only the elements defined in the definition file, and ignore the other ones.
In the test project [https://plnkr.co/edit/PWww2EV50SgYVmfEVpP9?p=preview](https://plnkr.co/edit/PWww2EV50SgYVmfEVpP9?p=preview), if we add a custom element under Service or Capability/Layer, it works (see wms_working_text.xml) but if we add a custom element under Capability (see wms_failing_test.xml) it fails (error are seen in the browser console).
Is there a rule about where the custom elements are allowed? Is it possible to add a custom element anywhere in the XML, making JSONIX to just ignore them if it doesn't know them from the definition file?

Thanks for your help!

@TropicCyril

**Comment by highsource** [comment]
Hi,

the problem is the `extendedCapabilities` property which "catches" the `Foo` element considering it to be an extension element. But then the property does not allow DOM and there's no mapping for `Foo` so it fails.

I see the following options:
* If you're OK to allow DOM, set `dom:true` for `extendedCapabilities`.
* Provide mapping for `Foo` if you'd prefer it unmarshalled as an object.
* Remove the `extendedCapabilities` property - `Foo` will be ignored then.

Since mappings are just JSON you can just post-process the loaded mapping:

https://plnkr.co/edit/cxyar5PVsiIiyULYDkBj?p=preview

Hope this helps.

Best wishes,
Alexey

**Comment by samuel-girard** [comment]
Thanks for your quick answer.
This totally fixes our problem.
