### ISSUE TITLE
Add new instance to a list

### ISSUE THREAD

**Issue by gitgabrio** [highsource/jsonix#220]
Hi,
I know that question has already been asked somehow (here, for example https://stackoverflow.com/questions/31101815/create-empty-object-from-xml-schema-using-jsonix) but I can not understand proposed solution (I'm a js noob).
I have a complex element (SCESIM) that contains some properties, some of which are lists. Is there a way (using Jsonix-all or the created xsd-specific SCESIM.js) to instantiate a new SCESIM object and populate its values, especially the list ones?

**Comment by highsource** [comment]
Not sure what is the best way to answer this.

With Jsonix you "simply" create a JS object which corresponds to the structure of your mappings.

Many users find it easier to start the other way roung:

* Create a sample XML like the one you'd like to marshall at the end.
* Unmarshal this XML with Jsonix.
* Print out the result in stringified form (`JSON.stringify(unmarshalledObject, null, 2)`).
* The will give you a pretty good idea of what your source object should look like so that Jsonix would be able to marshal it.

If you need more support please send a PR with a sample project under https://github.com/highsource/jsonix-support/tree/master/s/scesim.

Should ideally include schema generation and a test case. Here's an example:
https://github.com/highsource/jsonix-support/tree/master/r/reqif

**Comment by gitgabrio** [comment]
Thanks!
