### ISSUE TITLE
How to handle vendor options in SLD

### ISSUE THREAD

**Issue by bartvde** [highsource/jsonix#58]
So GeoServer has extended the SLD schema with something they call vendor option. It is basically an XML element to send extra information to the server. See also: http://docs.geoserver.org/latest/en/user/styling/sld-reference/labeling.html

What would be the easiest way to handle with with JSONIX?

See https://raw.githubusercontent.com/geotools/geotools/83876de0aa3774dd2e4ba58412bb2b74e257e24f/modules/extension/xsd/xsd-sld/src/main/resources/org/geotools/sld/bindings/StyledLayerDescriptor.xsd for their updated XML schema

TIA for any pointers

**Comment by highsource** [comment]
Hi,

I'm offline for a couple of days, will reply, when the Internet in my village will be fixed again. :)

Best wishes,
Alexey

**Comment by bartvde** [comment]
no problem, thanks for reporting back

**Comment by highsource** [comment]
OK, I'm more or less back online.

This is an interesting problem with several ways to approach. I haven't diff'd the schemas yet so I don't know the exact differences at the moment.

* The easiest is if you'd just compile the "customized" SLD schema. Either try to do it yourself or PR a new module in `ogc-schemas`, I'll take a look. This is probably the easiest and the fastest to get results, but not quite cool conceptually. It would be better if the "basic" SLD schema would be extended instead.
* This leads to the next solution possibility. Mappings are just plain JS objects so you can hack them as you wish. If you need a customized version of mappings, load `SLD_1_1_0` (or whatever version it is) and then just add/modify/remove types and properties you want to customize. Might make sense compiling the customized schema first and *then* manually extract the changes and add them to the "standard" schema. This is more work but feels better conceptually.
* (Not OOTB.) We could consider some kind of `redefine` functionality for Jsonix. Where you could load the mapping `A` with the mapping `Ax` which would redefine some types or properties in `A.MyType.myProp`. Does not feel easy to do though.
* (Not OOTB.) Mappingless approach. Adding some elements and attributes which were not defined in the mappings. I mean that Jsonix will marshal even those properties which were not defined in the mappings, with some default algorithm. This way you could add vendor extensions without having to change the mapping at all.

I think that at the moment you'll get the best results with the 1 or 2 option. Redefinitions might be also a good way but will need development. And mappingless mappings are definitely a good direction, but will also require development.

I actually think combining mappings and no-mappings is a way to go long-term. So that you could do the whole range from mappingless conversion to fully mapping-based conversion but also any combo in between.

Hope this helps.

**Comment by bartvde** [comment]
thanks for the feedback @highsource I'll take a crack at compiling the new schema first

**Comment by bartvde** [comment]
okay I got it to work, I added a type manually to the mappings for TextSymbolizer:

```
{
            n: 'vendorOption',
            en: 'VendorOption',
            ti: '.VendorOption'
          }
```

and then:

```
{
        ln: 'VendorOption',
        bti: '.ParameterValueType',
        ps: [{
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
        }]
     }
```

which allows me to define a vendorOption which is passed to the marshaller:

```
                    vendorOption: {
                        name: 'foo',
                        content: ['bar']
                   }
```

```
<sld:VendorOption name="foo">bar</sld:VendorOption>
```

Ideally I could do this without modifying the mapping file indeed.

**Comment by bartvde** [comment]
btw strictly speaking the base type is not ```bti: '.ParameterValueType'``` but I could not find how to define the value of the element node otherwise.

**Comment by highsource** [comment]
I'm not sure what you meant by *could not find how to define the value of the element node otherwise*.
You mean the textual content? The it's probably a value property which you need:

https://github.com/highsource/jsonix/wiki/Properties#value-property

`bti` is just an "extends" concept, nothing more. You inherit the properties from the base type class. Copy/paste would work as well.

**Comment by bartvde** [comment]
@highsource any pointer on how to make this a 1:n ?

**Comment by bartvde** [comment]
what I meant was how to get the ```bar``` part of the example below:

```
<sld:vendorOption name="foo">bar</sld:vendorOption>
```

**Comment by bartvde** [comment]
okay so you're saying I could leave out ```bti`` and pass on value instead of content?

**Comment by bartvde** [comment]
just tested the last assumption but then I get: ```<sld:VendorOption name="foo"/>``` when using:

```
 vendorOption: {
                        name: 'foo',
                        value: 'bar'
                    }
```

**Comment by highsource** [comment]
Yes, leave out `bti` and add a `content` property of type `value` (probably `t:'v'`).

Next 1:n. Either `collection:true` (probably won't work) or a [list type of strings](https://github.com/highsource/jsonix/wiki/Types#deriving-simple-types-by-list):

```typeInfo: {
            type: 'list',
            typeInfo: 'String'
        }
```

This wil generate `bar baz` for `['bar', 'baz']`.

**Comment by highsource** [comment]
Maybe if you PR a testcase to `ogc-schemas` scripts this woul be a bit easier to handle.
Somewhere here:

https://github.com/highsource/ogc-schemas/tree/master/scripts/tests/SLD/1.0.0

**Comment by bartvde** [comment]
Ah that works fine:

```
{
        ln: 'VendorOption',
        ps: [{
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
        }, {
            n: 'content',
            t: 'v'
        }]
     }
``` 

and:

```
                    vendorOption: {
                        name: 'foo',
                        content: 'bar'
                    }
```

now onto the 1:n

**Comment by bartvde** [comment]
@highsource wrt 1:n I want to pass on something like:

```
 vendorOption: [{
                        name: 'foo',
                        content: 'bar'
                    }, {
                        name: 'x',
                        content: 'y'
                    }]
```

I tried ```col: true``` to no avail

```
{
        ln: 'VendorOption',
        col: true,
        ps: [{
            n: 'name',
            an: {
              lp: 'name'
            },
            t: 'a'
        }, {
            n: 'content',
            t: 'v'
        }]
     }
```

**Comment by bartvde** [comment]
ah I got it to work, had to apply ```col: true``` at a different level

```
{
            n: 'vendorOption',
            en: 'VendorOption',
            col: true,
            ti: '.VendorOption'
          }
```

**Comment by highsource** [comment]
Ok, I see. Then you have to make the `vendorOption property` collection.

**Comment by highsource** [comment]
Yep, this is what I was about to write.

**Comment by highsource** [comment]
Can we close it now?

**Comment by bartvde** [comment]
Yep, thanks for all your help once again ;-)

An extra beer at FOSSGIS :+1:

**Comment by highsource** [comment]
:+1:
