### ISSUE TITLE
Request for clarification on XSD mappings

### ISSUE THREAD

**Issue by brutalhonesty** [highsource/jsonix#59]
Hello there,

I've got a use case in which I would like to use XSD files that Amazon provides external facing developers and turn them into JSON objects which I can populate with data.
Some example XSD files include: [amzn-base.xsd](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-base.xsd) and [product.xsd](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Product.xsd). 

I've used JaxB to take the XSD files and turn them into Java objects which I can set the values in. However, utilizing NodeJS for a current project, I'm looking to do a similar thing with a different library (this one). Could someone help me clarify if this project can be used to pass a XSD file to it and have it give me either JSON or JSON schema to which I can fill in/generate values and then convert to the XML needed?

Thanks!

**Comment by highsource** [comment]
Hi,

yes, this absolutely looks like a use case for Jsonix. Jsonix is basically pretty much like JAXB for JavaScript. Runs on Node.js (as well as in browsers).

What Jsonix does:

* First you'll generate mappings for your XML Schemas. This is very much like using XJC in JAXB, you give your schemas in and get mappings which describe XML<->JSON conversion. This is normally the hardest step but since you've already used JAXb for your schemas, this won't be a big problem.
* In the runtime you'll create a Jsonix context (`var context = new Jsonix.Context([Base, Product]);`) and the use it to create unmarshallers or marshallers to convert between XML and JSON. Pretty much like `JAXBContext`/marshaller/unmarshaller in JAXB.
* Thus you can build your payload JSON and marshall it in XML form (which will conform to your schemas) or unmarshal XML into JSON in the known format.
* And you'll be ablo to do all of this in Node.js. Runtime is pure JavaScript, schema compilation uses a shipped Java library.

What Jsonix does not do:

* It does not generate JSON Schema (yet).
* It does not generate JSON "blueprints" for you to fill in. You can take some blueprint XML, unmarshal it, `JSON.stringify` to the console and use that as JSON blueprint, this is what people usually do.

To get you started, here's a basic but complete "purchase order" example:

* https://github.com/highsource/jsonix/wiki/Working-Example
* https://github.com/highsource/jsonix/tree/master/nodejs/tests/po

Using Jsonix Schema Compiler:

* https://github.com/highsource/jsonix/wiki/Generating-Mappings-from-XML-Schemas
* https://github.com/highsource/jsonix-schema-compiler/wiki

I can help you to compile your first schemas and to get the basic things run, this is normally no big deal.

Best wishes,
Alexey

**Comment by brutalhonesty** [comment]
Hey Alexey,

Thanks for taking the time to give me this detailed description! I do NOT have any XML yet for the above XSD files and I'm looking for a way to get some generated some how. You mentioned that I would need blueprint XML to start with and I just don't have a working example of any for these files. 

I've been able to compile mappings for [Books.xsd](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Books.xsd) without an issue. However, when trying to compile [Product.xsd](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Product.xsd) I was getting null pointers. I figured it was because it was missing the extra XSD files required. I added them all in and now I'm getting errors that the schema cannot contain two global components. I remember coming across this issue in the past with my Java application and it required you to make a bindings.xjb file to decide which ones should be named what. Do you have an example of the bindings.xjb in which you fix the "multiple occurences" of a variable?

Thanks!

**Comment by brutalhonesty** [comment]
I believe I need something similar to this for each conflict but I'm not sure exactly what the syntax is to get it working.

Command:
```bash
$ java -jar node_modules/jsonix-schema-compiler/lib/jsonix-schema-compiler-full.jar -compact -logLevel TRACE -d mappings -p Product Product.xsd -b bindings.xjb

```
```xml
<!-- bindings.xjb -->
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jaxb:bindings
  version="2.1"
  xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
  xmlns:jsonix="http://jsonix.highsource.org/customizations"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"

  jaxb:extensionBindingPrefixes="xjc jsonix">

  <jaxb:bindings schemaLocation="amzn-base.xsd" node="/xs:schema">
    <jaxb:schemaBindings>
      <jxb:bindings node="//xs:simpleType[@name='SuperLongString']">
        <property name="AmznBaseSuperLongString" />
      </jxb:bindings>
    </jaxb:schemaBindings>
  </jaxb:bindings>

</jaxb:bindings>
```

**Comment by brutalhonesty** [comment]
I've updated the file and I'm getting the following errors now:

```bash
```

```xml
```

**Comment by highsource** [comment]
Hi,

yes you'll probably need to customize, I'll help you compile the schemas. This is the hardest part.

I was thinking to move this to the support project where we could work on these schemas:

* https://github.com/highsource/jsonix-support

But then I saw this in these schemas:

> AMAZON.COM CONFIDENTIAL.  This document and the information contained in it are
> confidential and proprietary information of Amazon.com and may not be reproduced,
> distributed or used, in whole or in part, for any purpose other than as necessary 
> to list products for sale on the www.amazon.com web site pursuant to an agreement
> with Amazon.com.

This is a bit worrying, I wouldn't like any legal problems.
I'm not quite sure how to proceed at the moment. I'll try to compile your schemas later on but under circumstances I can't collaborate in public repos.

Best wishes,
Alexey

**Comment by highsource** [comment]
After a brief look at the schemas they seem to be invalid. They define global elements an types which were already defined in `amzn-base.xsd`. Example:

`CameraPhoto.xsd`:

```
	<xsd:complexType name="PowerDimension">
		<xsd:simpleContent>
			<xsd:extension base="xsd:positiveInteger">
				<xsd:attribute name="unitOfMeasure" type="CameraPowerUnitOfMeasure" use="required"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
```

`amzn-base.xsd`:
```
	<xsd:complexType name="PowerDimension">
		<xsd:simpleContent>
			<xsd:extension base="Dimension">
				<xsd:attribute name="unitOfMeasure" type="PowerUnitOfMeasure" use="required"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
```

And that's in the same (empty) namespace. This is invalid from XML Schema PoV. I'll think about how it might be solved.

**Comment by brutalhonesty** [comment]
@highsource Thanks for taking a look. As far as the disclaimer, these XSDfiles are in the public domain, external facing. You can find the files in a Github [repo](https://github.com/dmichael/amazon-mws/blob/master/examples/xsd/) already as well as [Google](http://bit.ly/19K6E6J) (It's the 5th one down).

If you would like to take this request to [jsonix-support](https://github.com/highsource/jsonix-support), I'm completely fine with it.

As far as the empty namespace goes, I can't edit the XSD files incase they change the schema in the future. Is there something I can do to help try to get them working?

**Comment by highsource** [comment]
Ok, I'm fine with that. The worst case scenario is a DMCA takedown on jsonix-support but it's not big deal.

I think we can just strip amzn-base.xsd down to whatever other schemas need. Give me a few hours, I'll get something working. And if you could find some XML examples for these schemas, that would be very helpful.

**Comment by brutalhonesty** [comment]
@highsource I agree it would be helpful :) This is one of the issue I'm having. There are not a lot of example XML documents that conform to the schema.

I've got one or two but they are pretty small and don't encompass all the attributes.

None the less...

* [Product.xml](https://gist.github.com/b0073b1f01568b54d9e9.git) example for a book.


Note: All feeds eventually get wrapped into an amazon-envelope which the XSD is [here](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-envelope.xsd). The rest of the files that amzn-envelope needs to complete are in the same [directory](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/). I setup a simple wget script to get them all.
Eventually your directory structure will probably match the Github repo I [posted](https://github.com/dmichael/amazon-mws/blob/master/examples/xsd/) above.

```bash
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-base.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-header.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/CatPIL.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Customer.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FulfillmentCenter.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FulfillmentOrderCancellationRequest.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FulfillmentOrderRequest.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Image.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Inventory.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Item.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Listings.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Loyalty.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/MultiChannelOrderReport.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/NavigationReport.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Offer.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderAcknowledgement.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderAdjustment.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderFulfillment.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderNotificationReport.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderReport.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Override.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Price.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProcessingReport.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Product.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProductImage.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Relationship.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ReverseFeed.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/SettlementReport.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Store.xsd
wget https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/WebstoreItem.xsd
```

With these files being found, we not only have to compile Product.xsd and amzn-base.xsd, it seems we need to get amzn-envelope.xsd compiling with its "children" as well.

**Comment by highsource** [comment]
Ok, I've managed to compile your schemas:

* https://github.com/highsource/jsonix-support/tree/master/a/amzn

As I said, some of the schemas are invalid. Some types are defined in `amzn-base.xsd` as well as other schemas. I had to fix it and then it compiled without much problems.

Unfortunately "fixing" means patching a few XSD files. There are three ways to fix duplicate types:

* Remove the duplicate type from `amzn-base.xsd`.
* Remove the duplicate type from the specific schema.
* Rename the duplicate type in the specific schema.

At the moment I've removed duplicate types from `amzn-base.xsd` in all the occasions where these types were only used in one specific schema. I think there was exactly one case when a type in question was used in several schemas. In this case I've renamed it in on of the specific schemas.

As I see it, there is no way around this, schemas must be valid, otheriwise generation does not work, period. No customization would help. Fortunately the fix is rather trivial (removing duplicate types). I think a long-term solution should be a "patch" XSLT which would be applied to schemas. This would make it a bit easier to update schema versions. But as it stands now, it is also not a big deal to remove these types manually.

Now, I've also added a `package.json` for Node.js and a "roundtrip" nodeunit test. The tests unmarshalls/marshalls/unmarshalls an XML and checks if the data is still the same. This more or less ensures if unmarshalling/marshalling works. So far both XML files you've provided seem to work. This is the JSON you get:

```javascript
{
    "name": {
        "namespaceURI": "",
        "localPart": "AmazonEnvelope",
        "prefix": "",
        "key": "AmazonEnvelope",
        "string": "AmazonEnvelope"
    },
    "value": {
        "TYPE_NAME": "AMZN.AmazonEnvelope",
        "header": {
            "TYPE_NAME": "AMZN.Header",
            "documentVersion": "1.01",
            "merchantIdentifier": "M_EXAMPLE_123456"
        },
        "messageType": "Product",
        "purgeAndReplace": false,
        "message": [
            {
                "TYPE_NAME": "AMZN.AmazonEnvelope.Message",
                "messageID": 1,
                "operationType": "Update",
                "product": {
                    "TYPE_NAME": "AMZN.Product",
                    "sku": "56789",
                    "standardProductID": {
                        "TYPE_NAME": "AMZN.StandardProductID",
                        "type": "ASIN",
                        "value": "B0EXAMPLEG"
                    },
                    "productTaxCode": "A_GEN_NOTAX",
                    "descriptionData": {
                        "TYPE_NAME": "AMZN.Product.DescriptionData",
                        "title": "Example Product Title",
                        "brand": "Example Product Brand",
                        "description": "This is an example product description.",
                        "bulletPoint": [
                            "Example Bullet Point 1",
                            "Example Bullet Point 2"
                        ],
                        "msrp": {
                            "TYPE_NAME": "AMZN.CurrencyAmount",
                            "currency": "USD",
                            "value": 25.19
                        },
                        "manufacturer": "Example Product Manufacturer",
                        "itemType": "example-item-type"
                    },
                    "productData": {
                        "TYPE_NAME": "AMZN.Product.ProductData",
                        "health": {
                            "TYPE_NAME": "AMZN.Health",
                            "productType": {
                                "TYPE_NAME": "AMZN.Health.ProductType",
                                "healthMisc": {
                                    "TYPE_NAME": "AMZN.HealthMisc",
                                    "ingredients": [
                                        "Example Ingredients"
                                    ],
                                    "directions": "Example Directions"
                                }
                            }
                        }
                    }
                }
            }
        ]
    }
}
```

You can ignore prefix/key/string and `TYPE NAME`, you normally don't need them for marshalling.

So it looks like it works more or less well now. Please let me know if it works for you.

**Comment by highsource** [comment]
@brutalhonesty Did you have a chance to take a look at this? I'm wrapping up the release and am inclined to close the issue.

**Comment by brutalhonesty** [comment]
@highsource Sorry for the delay! I just met with my team to discuss this and it looks like it the XSD files appear to be invalid. We've removed extra elements and followed the same method you used to resolve this issue. Thanks for all your help!

**Comment by highsource** [comment]
@brutalhonesty Super, thanks for letting me know. Feel free to drop a note if you need further support with Jsonix or your schemas.
