### ISSUE TITLE
An element named "short" is mapped as "_short"

### ISSUE THREAD

**Issue by hokkos** [highsource/jsonix#63]
Hi,
it seems a xsd element named "short" is mapped in an unmarshalled json as "_short", same for "long" to "_long", is it because they are future reserved keywords ? Is there a list of all of them ?

Thanks.

**Comment by highsource** [comment]
Hi,

good question.

Current reserved words:

https://github.com/highsource/jsonix-schema-compiler/wiki/Reserved-Keywords

These are basically Java reserved words.

Coming in one of the future versions:

https://github.com/highsource/jsonix-schema-compiler/issues/31

The background is that Jsonix Schema Compiler is based on a Java code generation stack which corrects identifier names if they'll break Java syntax. We'd actually only need JavaScript reserved words, but that will the introduce discrepancies between the generated Java code and Jsonix mappings. So I'd better not reduce the list of reserved keywords. However a few JavaScript keywords are missing, I'll have [to add them](https://github.com/highsource/jsonix-schema-compiler/issues/31).

Best wishes,
Alexey

**Comment by hokkos** [comment]
I don't understand what problems it creates in Javascript, as object property name can be reserved keywords. So if I don't use Java, I don't care about his limitations, should there be a mode in the mapping compiler to not escape reserved keywords ?
I think I could repair the mapping files for all element where the name != elementName.

**Comment by highsource** [comment]
Oh. You're right. Property names can be arbitrary, reserved words are allowed. It'll work as long as it is an identifier name.

The problem is here the backing Java stack. If Jsonix Schema Compiler is used along with Java code generation, this will produce problems in Java code. But standalone it would be OK to drop this limitation.

Please file an issue if you want this functionality.

Next, for name !=elementName. [XML Name production](http://www.w3.org/TR/REC-xml/#NT-Name) is almost but not fully compatible to the [ECMAScript IdentifierName production](http://ecma-international.org/ecma-262/5.1/#sec-7.6).

I think we can do it as follows:

* Add an option to turn off Java reserved keywords. (Please file an issue.)
* Add an option to turn off JavaScript reserved words. (Please file an issue.)
* If property name is a valid `IdentifierName`, output it as is, otherwise as a string literal (`"My.Property"`).

I think both Java and JavaScript reserved words should be turned on/off via options. These options may have different default values depending on the environment (standalone compiler call or via Maven/Java).

**Comment by highsource** [comment]
ps. I have wrongly assumed property names must be identifiers, but they really may be identifier names.

**Comment by hokkos** [comment]
You can set or get properties with a["\""] it will have a key: " so there is no limit.
